### ISSUE TITLE
Checklist for Next `MiniProd`

### ISSUE THREAD

**Issue by alexbooth92** [DUNE/ND_Production#22]
This issue will be used to record, at a high level, must-do items before running the next `MiniProd`. It should be added to as and when new items come up.

- [x] Corrected TMS geometry. Problem described [here](https://dunescience.slack.com/archives/C0500L3MXCP/p1697834734574899).
- [x] Make sure `topVol` for fiducial events is correct with the new geometry.
- [x] Make sure `TPCActive_shape` (`larnd-sim`) is correct.
- [ ] Verify `rockBox` method is working as intended.
- [x] `larnd-sim`: in detector properties `yaml`, ensure that `tpc_offsets` are as in line with gdml as possible.

**Comment by alexbooth92** [comment]
Marking this as complete. The one unticked todo here should be opened as a separate issue about rock generation in general.
